services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run dev
    ports:
      - 3000:3000